export { default as Home } from './Home';
export { default as About } from './About';
export { default as Posts } from './Posts';
export { default as Post } from './Post';
export { default as Mypage } from './Mypage';
export { default as Channels } from './Channels';
export { default as Conference } from './Conference';
export { default as Direct } from './Direct';
export { default as DropOut } from'./DropOut';
export { default as CreateGroup } from './CreateGroup';