export { default as Home } from './Home';
export { default as About } from './About';
export { default as Posts } from './Posts';
export { default as Post } from './Post';
export { default as Mypage } from './Mypage';
export { default as Channels } from './Channels';
export { default as Conference } from './Conference';
export { default as DropOut } from'./DropOut';
export { default as CreateGroup } from './CreateGroup';
export { default as LeaveGroup } from './LeaveGroup';
export { default as DropGroup } from './DropGroup';
export { default as DirectMessage } from './DirectMessage';
export { default as myDirectmsg } from './myDirectmsg';